-- Generated by test/make-schema.ts — do not edit, and do not treat as a migration.
-- It is where backend/migrations arrives, for the browser tests to start from.
-- 43 objects, from 82 statements (3 already-there skipped).

CREATE TABLE IF NOT EXISTS users (
  id                            TEXT    PRIMARY KEY,
  name                          TEXT    NOT NULL,
  email                         TEXT    NOT NULL,
  password_hash                 TEXT    NOT NULL,
  profession                    TEXT,
  email_verified                INTEGER NOT NULL DEFAULT 0,


  email_verification_token_hash TEXT,
  email_verification_expires_at INTEGER,

  deleted_at                    INTEGER,
  created_at                    INTEGER NOT NULL,
  updated_at                    INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_active
  ON users(LOWER(email))
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_email_verification_token_hash
  ON users(email_verification_token_hash)
  WHERE email_verification_token_hash IS NOT NULL;
CREATE TABLE IF NOT EXISTS sessions (
  id          TEXT    PRIMARY KEY,
  user_id     TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT    NOT NULL UNIQUE,
  device_info TEXT,
  expires_at  INTEGER NOT NULL,
  created_at  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS password_resets (
  id         TEXT    PRIMARY KEY,
  user_id    TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT    NOT NULL UNIQUE,
  expires_at INTEGER NOT NULL,
  used_at    INTEGER,
  created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_password_resets_user_id ON password_resets(user_id);
CREATE TABLE IF NOT EXISTS projects (
  id         TEXT    PRIMARY KEY,
  user_id    TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT    NOT NULL,

  deleted_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
, last_device_id TEXT, last_device_name TEXT, heartbeat_at INTEGER, heartbeat_device_id TEXT, heartbeat_device_name TEXT, restored_snapshot_id TEXT, metadata TEXT);
CREATE INDEX IF NOT EXISTS idx_projects_user_active
  ON projects(user_id, updated_at)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_projects_deleted_at
  ON projects(deleted_at)
  WHERE deleted_at IS NOT NULL;
CREATE TABLE IF NOT EXISTS strips (
  id         TEXT    PRIMARY KEY,
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  label      TEXT,
  sort_order INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_strips_project_order ON strips(project_id, sort_order);
CREATE TABLE IF NOT EXISTS frames (
  id         TEXT    PRIMARY KEY,
  strip_id   TEXT    NOT NULL REFERENCES strips(id) ON DELETE CASCADE,
  label      TEXT,
  sort_order INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
, crop_w INTEGER, crop_h INTEGER, text_content TEXT, table_data TEXT, note TEXT, scribbles TEXT, changed_offline INTEGER NOT NULL DEFAULT 0, needs    TEXT, notes    TEXT, setup_id TEXT, content_changed_at INTEGER, version_label TEXT, strip_labels  TEXT, hidden        INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_frames_strip_order ON frames(strip_id, sort_order);
CREATE TABLE IF NOT EXISTS versions (
  id         TEXT    PRIMARY KEY,
  frame_id   TEXT    NOT NULL REFERENCES frames(id) ON DELETE CASCADE,
  label      TEXT,
  type       TEXT    NOT NULL,
  updated_at INTEGER NOT NULL
, note TEXT, tags     TEXT, content_changed_at INTEGER, hidden        INTEGER NOT NULL DEFAULT 0, starred       INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_versions_frame ON versions(frame_id, updated_at);
CREATE TABLE IF NOT EXISTS images (
  id         TEXT    PRIMARY KEY,
  version_id TEXT    NOT NULL UNIQUE REFERENCES versions(id) ON DELETE CASCADE,
  r2_key     TEXT    NOT NULL,
  width      INTEGER,
  height     INTEGER,
  updated_at INTEGER NOT NULL
, size_bytes   INTEGER, content_type TEXT, created_at   INTEGER);
CREATE TABLE IF NOT EXISTS drawings (
  id           TEXT    PRIMARY KEY,
  version_id   TEXT    NOT NULL UNIQUE REFERENCES versions(id) ON DELETE CASCADE,
  drawing_data TEXT    NOT NULL,
  updated_at   INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS project_members (
  id         TEXT    PRIMARY KEY,
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id    TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       TEXT    NOT NULL,
  invited_at INTEGER NOT NULL,
  UNIQUE(project_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members(user_id);
CREATE INDEX IF NOT EXISTS idx_images_created_at ON images(created_at);
CREATE TABLE IF NOT EXISTS analytics_events (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  ts       INTEGER NOT NULL,          
  event    TEXT    NOT NULL,          
  uid      TEXT,                      
  sid      TEXT    NOT NULL,          
  device   TEXT,                      
  browser  TEXT,                      
  pwa      INTEGER NOT NULL DEFAULT 0,
  country  TEXT,                      
  meta     TEXT                       
);
CREATE INDEX IF NOT EXISTS idx_ae_ts      ON analytics_events(ts);
CREATE INDEX IF NOT EXISTS idx_ae_uid     ON analytics_events(uid) WHERE uid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ae_sid     ON analytics_events(sid);
CREATE INDEX IF NOT EXISTS idx_ae_event   ON analytics_events(event);
CREATE TABLE IF NOT EXISTS analytics_sessions (
  sid        TEXT    PRIMARY KEY,      
  uid        TEXT,                     
  device     TEXT,
  browser    TEXT,
  pwa        INTEGER NOT NULL DEFAULT 0,
  country    TEXT,
  started_at INTEGER NOT NULL,        
  last_seen  INTEGER NOT NULL,        
  events     INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_as_uid ON analytics_sessions(uid) WHERE uid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_as_started ON analytics_sessions(started_at);
CREATE TABLE IF NOT EXISTS project_deletions (
  id         TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('frame', 'version')),
  entity_id  TEXT NOT NULL,
  deleted_at INTEGER NOT NULL,
  device_id  TEXT, arrived_at INTEGER,
  FOREIGN KEY (project_id) REFERENCES projects(id)
);
CREATE INDEX IF NOT EXISTS idx_deletions_project ON project_deletions(project_id);
CREATE INDEX IF NOT EXISTS idx_deletions_entity ON project_deletions(entity_id);
CREATE TABLE IF NOT EXISTS project_snapshots (
  id         TEXT    PRIMARY KEY,
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,


  tree_json  TEXT    NOT NULL,
  created_at INTEGER NOT NULL
, reason TEXT NOT NULL DEFAULT 'auto', continued_at INTEGER);
CREATE INDEX IF NOT EXISTS idx_snapshots_project_time
  ON project_snapshots(project_id, created_at);
CREATE TABLE IF NOT EXISTS frame_conflicts (
  id           TEXT    PRIMARY KEY,
  project_id   TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  frame_id     TEXT    NOT NULL REFERENCES frames(id) ON DELETE CASCADE,

  losing_json  TEXT    NOT NULL,



  device_name   TEXT,         
  made_at       INTEGER,      
  winner_device TEXT,         
  winner_made_at INTEGER,

  made_offline INTEGER NOT NULL DEFAULT 0,
  created_at   INTEGER NOT NULL,


  resolved_at  INTEGER,


  resolution   TEXT
);
CREATE INDEX IF NOT EXISTS idx_frame_conflicts_open
  ON frame_conflicts(project_id, resolved_at);
CREATE TABLE IF NOT EXISTS project_settings (
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  kind       TEXT    NOT NULL,
  item_id    TEXT    NOT NULL,
  value      TEXT,                     
  changed_at INTEGER NOT NULL,         
  deleted_at INTEGER, arrived_at INTEGER,
  PRIMARY KEY (project_id, kind, item_id)
);
CREATE INDEX IF NOT EXISTS idx_project_settings_project ON project_settings(project_id);
CREATE TABLE IF NOT EXISTS setting_conflicts (
  id           TEXT    PRIMARY KEY,
  project_id   TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  kind         TEXT    NOT NULL,     
  item_id      TEXT    NOT NULL,
  losing_json  TEXT    NOT NULL,     
  device_name  TEXT,                 
  made_at      INTEGER,              
  winner_device    TEXT,             
  winner_made_at   INTEGER,
  created_at   INTEGER NOT NULL,
  resolved_at  INTEGER,
  resolution   TEXT                  
);
CREATE INDEX IF NOT EXISTS idx_setting_conflicts_open
  ON setting_conflicts(project_id, resolved_at);
CREATE INDEX IF NOT EXISTS idx_project_settings_arrived
  ON project_settings(project_id, arrived_at);
CREATE INDEX IF NOT EXISTS idx_project_deletions_arrived
  ON project_deletions(project_id, arrived_at);
