// THE TEST DATABASE'S SCHEMA, BUILT FROM THE MIGRATIONS (#309).
//
// Run:  npm run e2e:schema
//
// `wrangler d1 migrations apply` cannot build a database from these migrations
// any more, and must not be blamed for it: several of them (0007*, 0019) were
// written against a production database that ALREADY had the column, so they say
// "add made_at" to a table that 0018 now creates with made_at in it. On
// production that was a no-op. On an empty database it is a duplicate column and
// everything stops.
//
// Migrations are never edited once they have run — that rule stays. So instead
// this walks them in order, one statement at a time, skipping exactly the two
// harmless complaints ("duplicate column", "already exists"), and writes out the
// schema that results. The browser tests load THAT.
//
// Which means the file it writes is not a migration and never becomes one: it is
// a photograph of where the migrations arrive.

import { DatabaseSync } from 'node:sqlite';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'migrations';
const db = new DatabaseSync(':memory:');
let applied = 0, tolerated = 0;

for (const file of readdirSync(dir).filter((f) => f.endsWith('.sql')).sort()) {
  const sql = readFileSync(join(dir, file), 'utf8');
  // Comments first, then the split — a `--` note containing a semicolon would
  // otherwise cut a statement in half. Same as the bench's reader.
  const withoutComments = sql
    .split('\n')
    .map((l) => (l.trim().startsWith('--') ? '' : l.replace(/\s--\s.*$/, '')))
    .join('\n');
  for (const stmt of withoutComments.split(';').map((x) => x.trim()).filter(Boolean)) {
    try { db.exec(stmt); applied++; } catch (e) {
      const msg = String((e as Error).message);
      if (/duplicate column name|already exists/i.test(msg)) { tolerated++; continue; }
      console.error(`\n${file}\n  ${stmt.slice(0, 120)}\n  ${msg}\n`);
      process.exit(1);
    }
  }
}

// AND THE COLUMNS NO MIGRATION EVER CREATED.
//
// `projects.metadata`, `frames.hidden`, `versions.starred` and a few others live
// on the production database but appear in no migration — 0007d and friends are
// comments saying "already exists on production. No-op." So a database built
// from the migrations alone is missing them, and the very first pull dies with
// `no such column: metadata`.
//
// The bench found this months ago and wrote them down in schema-drift.sql. The
// same file is applied here, for the same reason.
const drift = readFileSync(join('test', 'schema-drift.sql'), 'utf8')
  .split('\n')
  .map((l) => (l.trim().startsWith('--') ? '' : l.replace(/\s--\s.*$/, '')))
  .join('\n');
for (const stmt of drift.split(';').map((x) => x.trim()).filter(Boolean)) {
  try { db.exec(stmt); applied++; } catch (e) {
    if (/duplicate column name|already exists/i.test(String((e as Error).message))) { tolerated++; continue; }
    throw e;
  }
}

const rows = db.prepare(
  `SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'`,
).all() as Array<{ sql: string }>;

const out = [
  '-- Generated by test/make-schema.ts — do not edit, and do not treat as a migration.',
  '-- It is where backend/migrations arrives, for the browser tests to start from.',
  `-- ${rows.length} objects, from ${applied} statements (${tolerated} already-there skipped).`,
  '',
  // Safe to run twice: the tests may re-seed a database that is already there.
  ...rows.map((r) => `${r.sql
    .replace(/^CREATE TABLE /i, 'CREATE TABLE IF NOT EXISTS ')
    .replace(/^CREATE INDEX /i, 'CREATE INDEX IF NOT EXISTS ')
    .replace(/^CREATE UNIQUE INDEX /i, 'CREATE UNIQUE INDEX IF NOT EXISTS ')};`),
  '',
].join('\n');

writeFileSync('test/e2e-schema.sql', out);
console.log(`wrote test/e2e-schema.sql — ${rows.length} tables and indexes, `
  + `${tolerated} statements skipped as already-there`);
